[build]
  publish = "."

[dev]
  command = "node site-server.js"
  port = 8080

[[redirects]]
  from = "/api/*"
  to = ":env_API_URL/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
